# Generated by Django 5.0 on 2023-12-16 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='subcategories',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AddField(
            model_name='team',
            name='isTop',
            field=models.BooleanField(default=False, verbose_name='Топ'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(verbose_name='Стандартная цена'),
        ),
        migrations.AlterField(
            model_name='services',
            name='subcategorу',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subcategories', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='services',
            name='top_price',
            field=models.IntegerField(verbose_name='Топ цена'),
        ),
        migrations.AlterField(
            model_name='services',
            name='type',
            field=models.CharField(choices=[('М', 'Мужская'), ('Ж', 'Женская'), ('Д', 'Детская')], max_length=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Фамилия/имя'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post',
            field=models.CharField(max_length=70, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='team',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
